version: '3.7'

services:

  daily:
    build:
      context: ./services/daily
      dockerfile: Dockerfile
    volumes:
      - './services/daily:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=my_precious
